name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy.io
  - pandas
  - random
  - math
